apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: solr-ss
spec:
  selector:
    matchLabels:
      app: solr-app # has to match .spec.template.metadata.labels
  serviceName: "solr-service"
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        app: solr-app # has to match .spec.selector.matchLabels
        version: "5"
    spec:
      terminationGracePeriodSeconds: 120
      restartPolicy: Always
      volumes:
      - name: volsolr
        emptyDir: {}
      containers:
      - name: solr
        image: solr:latest
        command: ["/bin/sh"]
        args: ["-c", "SOLR_HOST=`hostname -f` solr-foreground"]
        volumeMounts:
        - name: volsolr
          mountPath: /store
        ports:
        - name: solr-port
          containerPort: 2181
        env:
          - name: SOLR_HOME
            valueFrom:
              configMapKeyRef:
                name: solr-config
                key: solrHome
          - name: SOLR_PORT
            valueFrom:
              configMapKeyRef:
                name: solr-config
                key: solrPort
          - name: ZK_HOST
            valueFrom:
              configMapKeyRef:
                name: solr-config
                key: zkHost
          - name: SOLR_LOGS_DIR
            valueFrom:
              configMapKeyRef:
                name: solr-config
                key: solrLogsDir
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "curl --fail http://localhost:${SOLR_PORT}/solr/"
          initialDelaySeconds: 10
          timeoutSeconds: 5
      initContainers:
      - name: init-solr-data
        image: busybox
        command: ['sh', '-c', 'mkdir -p /store/data && chown 8983:8983 /store/data']
        volumeMounts:
        - name: volsolr
          mountPath: /store
      - name: init-solr-logs
        image: busybox
        command: ['sh', '-c', 'mkdir -p /store/logs && chown 8983:8983 /store/logs']
        volumeMounts:
        - name: volsolr
          mountPath: /store
      - name: init-solr-xml
        image: solr:latest
        command: ['sh', '-c', '[ ! -f /store/data/solr.xml ] && cp /opt/solr/server/solr/solr.xml /store/data/solr.xml || true']
        volumeMounts:
        - name: volsolr
          mountPath: /store

